title: What is Life
description: Yet another "Quest for the Meaning of Life" blog, this time taken on by a biologist with fetish for math and computers.
author: Jan Kočí

theme: minima

header_pages:
  - about.md
  - tutorials.md
  
