title: Everything Evolutionary
description: "Everything is better with evolution in the mix!"
author: Jan Kočí
icon: 🐊

#theme: minima

#minima:
#  skin: solarized #auto

remote_theme: alshedivat/al-folio@1.2 #jekyll/minima@1e8a445
plugins:
  - jekyll-remote-theme

header_pages:
  - tutorials.md
  - about_me.md

show_excerpts: false

kramdown:
  parse_block_html: true

