title: Everything Evolutionary
description: "Everything is better with evolution in the mix!"
author: Jan Kočí

#theme: minima

minima:
  skin: solarized

remote_theme: jekyll/minima
plugins:
  - jekyll-remote-theme

header_pages:
  - tutorials.md
  - about_me.md

show_excerpts: false

kramdown:
  parse_block_html: true

