title: Jan Kočí's home
description: "Everything is better with evolution in the mix!"
author: Jan Kočí

theme: minima

header_pages:
  - tutorials.md

show_excerpts: false

kramdown:
  parse_block_html: true

